import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/components/providers/QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      {/* 한국어 설정 */}

      <body className={`${geistSans.variable} antialiased bg-gray-100`}>
        <QueryProvider>
          {/* 전체 배경은 회색으로 줍니다. */}
          <div className="relative mx-auto min-h-screen max-w-[450px] bg-white shadow-2xl">
            {/* 중앙에 모바일 사이즈 박스를 고정합니다. */}
            {children}
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
